---
- hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: create file
      file:
        path: /tmp/test
        state: directory

    - name: copy file
      copy: 
        src: /etc/fstab
        dest: /tmp/test

    - name: restart service
      service:
        name: crond
        state: restarted

    - name: install package
      yum:
        name: vsftpd
        state: present
